### ISSUE TITLE
compiler panic `ast.Expr is *ast.IndexExpr, not *ast.Ident`

### ISSUE THREAD

**Issue by jozef-slezak** [gopherjs/gopherjs#1178]
Error building graphjin/wasm https://github.com/dosco/graphjin/blob/master/wasm/main.go using gopherjs.

unexpected compiler panic while building package "main": interface conversion: ast.Expr is *ast.IndexExpr, not *ast.Ident

```
C:\workspace\graphql\graphjin\graphjin-master20221217\wasm>gopherjs.exe build "main.go"
←[31m[compiler panic]  unexpected compiler panic while building package "main": interface conversion: ast.Expr is *ast.IndexExpr, not *ast.Ident

Original stack trace:
   goroutine 1 [running]:
  runtime/debug.Stack()
        C:/Users/DESKTOP-1C942AU/scoop/apps/go/current/src/runtime/debug/stack.go:24 +0x65
  github.com/gopherjs/gopherjs/compiler.bailout(...)
        C:/Users/DESKTOP-1C942AU/go/pkg/mod/github.com/gopherjs/gopherjs@v1.18.0-beta1/compiler/utils.go:814
  github.com/gopherjs/gopherjs/compiler.Compile.func1()
        C:/Users/DESKTOP-1C942AU/go/pkg/mod/github.com/gopherjs/gopherjs@v1.18.0-beta1/compiler/package.go:138 +0x129
```

**Comment by nevkontakte** [comment]
This error is typical when trying to build code that uses generics, which are not currently supported by GopherJS. Feel free to follow #1013 to be notified when support is ready.
