### ISSUE TITLE
Node's require fails on testing

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#157]
e.g. After installing gl library like this

```
npm install --global gl
```

, execute this:

```go
package foo_test

import (
        "github.com/gopherjs/gopherjs/js"
        "testing"
)

func TestFoo(t *testing.T) {
        gl := js.Global.Call("require", "gl")
        print(gl)
}
```
```
gopherjs test
```

, failing with this message:
```
--- FAIL: TestFoo (0.01s)
fatal error: all goroutines are asleep - deadlock!

/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.118546901:1454
        throw err;
              ^
JavaScript error: Cannot find module 'gl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at $packages._/Users/hajimehoshi/tmp/test_test.$pkg.TestFoo [as F2] (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.118546901:17293:16)
    at $blocking_F (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.118546901:16266:13)
    at $blocking_tRunner (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.118546901:16958:83)
    at goroutine (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.118546901:1442:19)
    at null._onTimeout (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.118546901:1498:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
FAIL    _/Users/hajimehoshi/tmp/test    0.212s
```

With regular ``gopherjs build`` and ``node``, ``require`` worked.

**Comment by neelance** [comment]
Are you sure that GopherJS is using the same node version? It uses the version on your `PATH`, but if you for example use `nvm` then `node` and `npm` in your shell may point to a different installation.

**Comment by hajimehoshi** [comment]
> Are you sure that GopherJS is using the same node version? 

Yes. I'm using Mac OS X and node installed with Homebrew. There is only one ``node`` in my machine.

**Comment by hajimehoshi** [comment]
> With regular ``gopherjs`` build and ``node``, require worked.

Probably, ``$HOME/node_modules/gl`` was present. That command doesn't work after removing ``$HOME/node_modules/gl``. ``node`` called in ``gopherjs test`` was executed in a temporary directory, and that's the reason why ``gl`` couldn't be found there.

Finally, ``NODE_PATH=/usr/local/lib/node_modules gopherjs test`` worked well, but isn't ``/usr/local/lib/node_modules`` the default path? This is not the problem of GopherJS anyway. Sorry for confusion.
