### ISSUE TITLE
Comparing structs including js.Object fails

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#159]
```go
package main

import (
	"fmt"
	"github.com/gopherjs/gopherjs/js"
)

type Foo struct {
	js.Object
}

func main() {
	var f1 Foo
	var f2 Foo
	fmt.Println(f1 == f2)
}
```
The above program fails with this message:
```
$ gopherjs run test.go

/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:1457
        throw err;
              ^
TypeError: Cannot read property 'constructor' of null
    at $interfaceIsEqual (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:413:8)
    at $equal (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:403:12)
    at $equal (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:397:12)
    at $packages.main.main (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:12488:40)
    at $init_main (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:12501:3)
    at goroutine (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:1445:19)
    at $schedule (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:1487:5)
    at goroutine (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:1449:9)
    at $schedule (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:1487:5)
    at $go (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:1476:3)
    at /private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:12507:1
    at Object.<anonymous> (/private/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/test.go.195292389:12510:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by hajimehoshi** [comment]
:+1:
