### ISSUE TITLE
crash "panic: Zero value for untyped nil."

### ISSUE THREAD

**Issue by glycerine** [gopherjs/gopherjs#181]
on go version go1.4 darwin/amd64.
on gopherjs e036e97665606ce2f53ea5814973696ffadf4588

Haven't narrowed this down yet, but "gopherjs build" results in crash on one project (haven't tried it on this project before).

Suggestions?
~~~
panic: Zero value for untyped nil. [recovered]
	panic: Zero value for untyped nil.

goroutine 1 [running]:
golang.org/x/tools/go/types.(*Checker).handleBailout(0xc2080ae680, 0xc208edc328)
	/Users/jasona/go/src/golang.org/x/tools/go/types/check.go:218 +0xfc
github.com/gopherjs/gopherjs/compiler.(*funcContext).zeroValue(0xc209786fa0, 0x72ab28, 0x6652a0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/utils.go:152 +0x93d
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc209786fa0, 0x72b688, 0xc20863fe60, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:759 +0x26ef
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateImplicitConversion(0xc209786fa0, 0x72b688, 0xc20863fe60, 0x72ab28, 0x6652a0, 0x306920)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1094 +0x27c
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc209786fa0, 0x72b768, 0xc209559860, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:449 +0x1358b
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc209786fa0, 0x72b768, 0xc20953fe00, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:282 +0xa606
github.com/gopherjs/gopherjs/compiler.*funcContext.(github.com/gopherjs/gopherjs/compiler.translateExpr)·fm(0x72b768, 0xc20953fe00, 0xc2095bfa40)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/statements.go:64 +0x3b
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateBranchingStmt(0xc209786fa0, 0xc20894aaa0, 0x1, 0x1, 0x0, 0xc208ed8eb8, 0x0, 0x0, 0xc20894a700)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/statements.go:566 +0x1b82
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc209786fa0, 0x72b880, 0xc209541a80, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/statements.go:64 +0xe76d
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc209786fa0, 0xc2095594d0, 0x3, 0x3)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·029()
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:713 +0x166b
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc209786fa0, 0x1, 0xc208ed9b60, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/utils.go:53 +0x9f
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc2086384c0, 0xc2095594d0, 0x3, 0x3, 0xc2085580a0, 0xc20965a810, 0xc20924c420, 0xc20954855a, 0x6, 0x0, ...)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:717 +0x79e
github.com/gopherjs/gopherjs/compiler.func·028(0xc2090fd160, 0x1f, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:549 +0xf18
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc2085580a0, 0xc20953fec0, 0xc20924c420, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:577 +0x7bc
github.com/gopherjs/gopherjs/compiler.func·021()
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:328 +0x4c
github.com/gopherjs/gopherjs/compiler.func·016(0xc209559410, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:226 +0xa4
github.com/gopherjs/gopherjs/compiler.Compile(0xc20808b5c1, 0x21, 0xc209580700, 0x19, 0x20, 0xc2094dfdc0, 0xc20802aec0, 0xc20924fb00, 0x2, 0x0, ...)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:329 +0x51e7
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc20800ab80, 0xc208fffa90, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/build/build.go:447 +0xf7d
github.com/gopherjs/gopherjs/build.(*Session).ImportPackage(0xc20800ab80, 0xc20808b5c1, 0x21, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/build/build.go:356 +0x5ea
github.com/gopherjs/gopherjs/build.*Session.ImportPackage·fm(0xc20808b5c1, 0x21, 0x18d335, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/build/build.go:260 +0x4d
github.com/gopherjs/gopherjs/compiler.func·012(0xc20807a5a0, 0xc20808b5c1, 0x21, 0x21, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:80 +0x63
golang.org/x/tools/go/types.(*Checker).collectObjects(0xc2080ae680)
	/Users/jasona/go/src/golang.org/x/tools/go/types/resolver.go:182 +0x29e4
golang.org/x/tools/go/types.(*Checker).Files(0xc2080ae680, 0xc20803eb00, 0x9, 0x10, 0x0, 0x0)
	/Users/jasona/go/src/golang.org/x/tools/go/types/check.go:228 +0xba
golang.org/x/tools/go/types.(*Config).Check(0xc2080c5400, 0x412430, 0x4, 0xc208090a00, 0xc20803eb00, 0x9, 0x10, 0xc2080bd090, 0x8d212, 0x0, ...)
	/Users/jasona/go/src/golang.org/x/tools/go/types/api.go:340 +0xbb
github.com/gopherjs/gopherjs/compiler.Compile(0x412430, 0x4, 0xc20803eb00, 0x9, 0x10, 0xc208090a00, 0xc20802aec0, 0x0, 0x72b600, 0x0, ...)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/compiler/package.go:97 +0x52d
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc20800ab80, 0xc208093590, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/build/build.go:447 +0xf7d
github.com/gopherjs/gopherjs/build.(*Session).BuildDir(0xc20800ab80, 0xc20803bf00, 0x3d, 0xc20803bf00, 0x3d, 0x0, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/build/build.go:294 +0x442
main.func·001(0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/tool.go:76 +0xcc
main.handleError(0xc208eddb18, 0xc20803bf40, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/tool.go:431 +0x2f
main.func·002(0xc208068000, 0x673910, 0x0, 0x0)
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/tool.go:124 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc208068000, 0x673910, 0x0, 0x0, 0x0, 0x0)
	/Users/jasona/go/src/github.com/spf13/cobra/command.go:399 +0x38d
github.com/spf13/cobra.(*Command).findAndExecute(0xc208068780, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
	/Users/jasona/go/src/github.com/spf13/cobra/command.go:366 +0xd4
github.com/spf13/cobra.(*Command).Execute(0xc208068780, 0x0, 0x0)
	/Users/jasona/go/src/github.com/spf13/cobra/command.go:452 +0xab3
main.main()
	/Users/jasona/go/src/github.com/gopherjs/gopherjs/tool.go:427 +0x1551

~~~

**Comment by neelance** [comment]
Thanks for reporting this. Unfortunately the stack trace is not enough for me to pin down the problem. Could you try to create a small test case that causes the crash?

**Comment by glycerine** [comment]
@neelance Hi Richard,
here you go, it looks like something in the go-tigertonic package is causing the problem.
- Jason

~~~
package main

import "github.com/rcrowley/go-tigertonic"

func main() {
}

type WebServer struct {
    mux *tigertonic.TrieServeMux
}
~~~
