### ISSUE TITLE
panic when using multiple assignment to a map

### ISSUE THREAD

**Issue by nlacasse** [gopherjs/gopherjs#221]
Code that assigns to a map and another variable simultaneously causes gopherjs to panic.

It looks like `translateAssign` does not handle the case when a map index expression is on the LHS of a multiple assignment.

test/main.go:
```
package main

import (
	"fmt"
)

func main() {
	x := 0
	m := map[string]string{}

	x, m["foo"] = 5, "bar"

	fmt.Printf("x=%v, m=%v\n", x, m)
}
```

```
gopherjs build test

panic: Unhandled lhs type: *types.Map

goroutine 1 [running]:
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateAssign(0xc2088166e0, 0x7f0904a5efc0, 0xc208607200, 0xc2088c8ef0, 0x6, 0x7f0904a5cc68, 0xc76e00, 0x0, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/statements.go:775 +0x18d1
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc2088166e0, 0x7f0904a5e7c0, 0xc208e26340, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/statements.go:371 +0xc698
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc2088166e0, 0xc208e26380, 0x4, 0x4)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·029()
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:668 +0x974
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc2088166e0, 0x1, 0xc209be1a30, 0x0, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/utils.go:64 +0x9f
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc208f63c20, 0x0, 0x0, 0x0, 0xc208607230, 0xc208816580, 0xc208607470, 0xc20894ef60, 0xc2088c86a4, 0x4, ...)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:669 +0x6ef
github.com/gopherjs/gopherjs/compiler.func·028(0xc2088c86a4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:566 +0xf07
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc208816580, 0xc208607260, 0xc20894ef60, 0x0, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:575 +0x3de
github.com/gopherjs/gopherjs/compiler.func·021()
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:341 +0x4c
github.com/gopherjs/gopherjs/compiler.func·016(0xc208607aa0, 0x0, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:231 +0xa7
github.com/gopherjs/gopherjs/compiler.Compile(0x7fff583cb887, 0x4, 0xc2093248a0, 0x1, 0x1, 0xc208e47c40, 0xc20802d190, 0x0, 0xc20802d280, 0x0, ...)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/compiler/package.go:342 +0x4ff0
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc208020900, 0xc208031720, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/build/build.go:459 +0xf50
main.func·001(0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/tool.go:117 +0x4f3
main.handleError(0xc209be3bc8, 0xc208098000, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/tool.go:565 +0x2f
main.func·002(0xc208038680, 0xc2080208e0, 0x1, 0x2)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/tool.go:128 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc208038680, 0xc208020820, 0x2, 0x2, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/spf13/cobra/command.go:473 +0x64e
github.com/spf13/cobra.(*Command).Execute(0xc2080391e0, 0x0, 0x0)
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/spf13/cobra/command.go:535 +0x18d
main.main()
	/usr/local/google/home/nlacasse/code/gophertest/src/github.com/gopherjs/gopherjs/tool.go:448 +0x1681
```

**Comment by neelance** [comment]
Thanks for reporting!
