### ISSUE TITLE
`gopherjs build` panic on js tagged methond invoking

### ISSUE THREAD

**Issue by Archs** [gopherjs/gopherjs#228]
the fllowing program panic when doing `gopherjs build`

Go version: `go version go1.4.2 linux/amd64`

gopherjs version: `commit d60db54d81979234899c62702870360fd84ac03c
Author: Richard Musiol <mail@richard-musiol.de>
Date:   Mon May 18 00:21:41 2015 +0200

    replaced gcexporter by golang.org/x/tools/go/importer
`

the latest gopherjs `commit 472b955f1cbb37c19f3ffded44eade0ee75ba728` panics either

```Go
package main

import (
	"github.com/gopherjs/gopherjs/js"
)

type A struct {
	*js.Object
	Method func() `js:"Method"` // js tag with method invoke, panic
	// Method func() // this is fine
}

func main() {
	a := &A{
		Object: js.Global.Get("Object").New(),
		Method: func() {
			println("hello")
		},
	}
	println(a.Method) // this is fine
	a.Method()        // this cause panic
}
```

stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x55334f]

goroutine 1 [running]:
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc208068790, 0x7f9049eeab30, 0xc20809a040, 0x0)
    github.com/gopherjs/gopherjs/compiler/expressions.go:653 +0x145df
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc208068790, 0x7f9049eeaba0, 0xc20802b3b0, 0x0)
    github.com/gopherjs/gopherjs/compiler/statements.go:417 +0xd30b
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc208068790, 0xc20809a080, 0x3, 0x4)
    github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·029()
    github.com/gopherjs/gopherjs/compiler/package.go:668 +0x974
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc208068790, 0x1, 0xc208131840, 0x0, 0x0, 0x0)
    github.com/gopherjs/gopherjs/compiler/utils.go:64 +0x9f
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc20801f320, 0x0, 0x0, 0x0, 0xc20806b650, 0xc208068630, 0xc2080bc5d0, 0xc2080519e0, 0xc20802ae50, 0x4, ...)
    github.com/gopherjs/gopherjs/compiler/package.go:669 +0x6ef
github.com/gopherjs/gopherjs/compiler.func·028(0xc20802ae50, 0x4, 0x0, 0x0, 0x0)
    github.com/gopherjs/gopherjs/compiler/package.go:566 +0xf07
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc208068630, 0xc20806b680, 0xc2080519e0, 0x0, 0x0, 0x0)
    github.com/gopherjs/gopherjs/compiler/package.go:575 +0x3de
github.com/gopherjs/gopherjs/compiler.func·021()
    github.com/gopherjs/gopherjs/compiler/package.go:341 +0x4c
github.com/gopherjs/gopherjs/compiler.func·016(0xc2080554d0, 0x0, 0x0, 0x0)
    github.com/gopherjs/gopherjs/compiler/package.go:231 +0xa7
github.com/gopherjs/gopherjs/compiler.Compile(0x985410, 0x4, 0xc20802e140, 0x1, 0x1, 0xc20802c540, 0xc20802b4a0, 0xc208034d00, 0x8179c0, 0x0, ...)
    github.com/gopherjs/gopherjs/compiler/package.go:342 +0x4ff0
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc20801f2e0, 0xc208031590, 0x0, 0x0)
    github.com/gopherjs/gopherjs/build/build.go:447 +0xf50
github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc20801f2e0, 0xc20802b480, 0x1, 0x1, 0xc20801f300, 0x11, 0xc20801f100, 0x12, 0x0, 0x0)
    github.com/gopherjs/gopherjs/build/build.go:323 +0x3d7
main.func·001(0x0, 0x0)
    github.com/gopherjs/gopherjs/tool.go:101 +0xc05
main.handleError(0xc208133af8, 0xc20802df40, 0x0)
    github.com/gopherjs/gopherjs/tool.go:565 +0x2f
main.func·002(0xc208072280, 0xc20802b480, 0x1, 0x1)
    github.com/gopherjs/gopherjs/tool.go:128 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc208072280, 0xc20802b440, 0x1, 0x1, 0x0, 0x0)
    github.com/spf13/cobra/command.go:444 +0x410
github.com/spf13/cobra.(*Command).findAndExecute(0xc208072c80, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
    github.com/spf13/cobra/command.go:408 +0xd4
github.com/spf13/cobra.(*Command).Execute(0xc208072c80, 0x0, 0x0)
    github.com/spf13/cobra/command.go:497 +0xb1b
main.main()
    github.com/gopherjs/gopherjs/tool.go:448 +0x17c6
```

**Comment by shurcooL** [comment]
Here's a stack trace using latest commit 472b955f1cbb37c19f3ffded44eade0ee75ba728 (your stack trace appears not to be from an older one):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1549ed]

goroutine 1 [running]:
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc2080ba160, 0x951af0, 0xc20809c3c0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/expressions.go:663 +0x1479d
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc2080ba160, 0x951b60, 0xc20802b6d0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/statements.go:426 +0xd7f5
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc2080ba160, 0xc20809c400, 0x3, 0x4)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·029()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:667 +0x974
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc2080ba160, 0x1, 0xc208129940, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/utils.go:64 +0x9f
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc20801f700, 0x0, 0x0, 0x0, 0xc2080794d0, 0xc2080ba000, 0xc208091110, 0xc20805f200, 0xc20802b520, 0x4, ...)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:668 +0x6ef
github.com/gopherjs/gopherjs/compiler.func·028(0xc20802b520, 0x4, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:565 +0xf07
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc2080ba000, 0xc208079500, 0xc20805f200, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:574 +0x3de
github.com/gopherjs/gopherjs/compiler.func·021()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:340 +0x4c
github.com/gopherjs/gopherjs/compiler.func·016(0xc208091e00, 0x0, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:230 +0xa7
github.com/gopherjs/gopherjs/compiler.Compile(0x5801b0, 0x4, 0xc20802e178, 0x1, 0x1, 0xc20802df80, 0xc20802b310, 0x0, 0xc207ffd504, 0x0, ...)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/compiler/package.go:341 +0x4ee8
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc20801efa0, 0xc208031590, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/build/build.go:459 +0xf50
github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc20801efa0, 0xc20802b2f0, 0x1, 0x1, 0xc20802b296, 0x6, 0xc20801ed80, 0x15, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/build/build.go:334 +0x3d7
main.func·001(0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:101 +0xc05
main.handleError(0xc20812bbc8, 0xc20802df00, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:567 +0x2f
main.func·002(0xc208036820, 0xc20802b2f0, 0x1, 0x1)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:128 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc208036820, 0xc20802b2c0, 0x1, 0x1, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0xc208037380, 0x0, 0x0)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/tool.go:450 +0x1681

goroutine 5 [runnable]:
text/template/parse.lexText(0xc208060080, 0x6f3db0)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208060080)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac
```

That nil pointer dereference is happening on [this line](http://gotools.org/github.com/gopherjs/gopherjs/compiler?rev=472b955f1cbb37c19f3ffded44eade0ee75ba728#expressions-go-L663).

**Comment by shurcooL** [comment]
I think the issue is in this expression:

```Go
sig.Results().At(0).Type()
```

The func you've provided has no return types, so `sig.Results().At(0)` is `nil`.

I can see that if you change the signature of `Method` from `func()` to something like `func() int`, then the panic does not occur. Of course, this is still a real issue, I'm just sharing information I found.

**Comment by shurcooL** [comment]
Actually, if I'm reading this correctly, that `sig.Results().At(0).Type()` is an extraneous argument that is not even used:

```Go
c.formatExpr("%e.%s.%s(%s)", f.X, strings.Join(fields, "."), jsTag, externalizeArgs(e.Args)), sig.Results().At(0).Type()
```

There are 4 arguments in the format string (%e, %s, %s and %s), and 5 values provided. I think `sig.Results().At(0).Type()` is not used at all and should be removed.

I'll look into git blame, I'm guessing it's a left over from some refactoring.

**Comment by shurcooL** [comment]
Okay, I've tested my simple fix (mentioned in https://github.com/gopherjs/gopherjs/issues/228#issuecomment-105060282) and while it fixes the compiler panic, it's not enough to completely fix the issue.

With that change, the original program with the following modification works correctly:

```Go
a := &A{
	Object: js.Global.Get("Object").New(),
	/*Method: func() {
	    println("hello")
	},*/ // This gives: Uncaught TypeError: a.Object.Method is not a function.
}
a.Object.Set("Method", func() {
	println("hello")
}) // This works now.
```

Without my fix, the compiler panics on the above too.

It seems there's two ways to set a property of a `*js.Object`, via `js.Object.Set` or via initializing the struct with a js tag. It will need some additional changes to make it work in all cases.

**Comment by shurcooL** [comment]
5dbbd966abe3146d46c19528b46c07aba1db6563 fixes the panic, and allows the modified code I posted in previous comment to run as expected.

The original code still produces `Uncaught TypeError: a.Object.Method is not a function` runtime error. I'm not sure if that's intended or not?

**Comment by Archs** [comment]
The original code still produces Uncaught TypeError: a.Object.Method is not a function runtime error.     
    I'm not sure if that's intended or not?"

I thiks this relate to https://github.com/gopherjs/gopherjs/issues/114#issuecomment-60552704

Thank you all for you quick fix :+1:
