### ISSUE TITLE
Compiling error "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by Splizard** [gopherjs/gopherjs#244]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x55bcb3]

goroutine 1 [running]:
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc208ea7600, 0x7f2007262b38, 0xc20904a8a0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:506 +0x1d8e3
github.com/gopherjs/gopherjs/compiler.func·010(0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1256 +0x197
github.com/gopherjs/gopherjs/compiler.func·011(0x6500, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1277 +0x563
github.com/gopherjs/gopherjs/compiler.func·008(0xc208d23ef0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1211 +0xfd
github.com/gopherjs/gopherjs/compiler.(*funcContext).formatExprInternal(0xc208ea7600, 0x981990, 0x8, 0xc208d23e90, 0x3, 0x3, 0xc2094a6d00, 0xc2094a6d70)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1330 +0x4d2
github.com/gopherjs/gopherjs/compiler.(*funcContext).formatExpr(0xc208ea7600, 0x981990, 0x8, 0xc208d23e90, 0x3, 0x3, 0xc208b49c79)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1191 +0x5f
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc208ea7600, 0x7f2007262da0, 0xc208d23e30, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:341 +0xd4f5
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateImplicitConversion(0xc208ea7600, 0x7f2007262da0, 0xc208d23e30, 0x7f2007261c68, 0xc64da0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1077 +0x27c
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateAssignOfExpr(0xc208ea7600, 0x7f2007262b38, 0xc20904a8a0, 0x7f2007262da0, 0xc208d23e30, 0x7f2007261c68, 0xc64da0, 0xc2080bba00, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:730 +0xb07
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc208ea7600, 0x7f2007262c50, 0xc208e6c480, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:348 +0xb47d
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc208ea7600, 0xc208bd6fd0, 0x1, 0x1)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc208ea7600, 0x7f2007262e10, 0xc208d23e60, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:37 +0xd772
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc208ea7600, 0xc208e6c3c0, 0x4, 0x4)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·047()
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:643 +0xb3
github.com/gopherjs/gopherjs/compiler.(*funcContext).Indent(0xc208ea7600, 0xc2094b0150)
	/Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:56 +0x34
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateBranchingStmt(0xc208ea7600, 0xc208bd6a40, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc208bd6900)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:647 +0x15ba
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc208ea7600, 0x7f2007262dd8, 0xc2080a0940, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:64 +0xddf2
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc208ea7600, 0xc2080bc5c0, 0x1, 0x1)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·029()
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:667 +0x974
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc208ea7600, 0x1, 0xc2094b19c8, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:64 +0x9f
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc2080b7940, 0xc2094b1c80, 0x1, 0x1, 0xc2080ba660, 0xc208ea6f20, 0xc209007b90, 0xc208be2480, 0xc208d237d0, 0x22, ...)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:668 +0x6ef
github.com/gopherjs/gopherjs/compiler.func·028(0xc208d237d0, 0x22, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:565 +0xf07
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc208ea6f20, 0xc2080ba690, 0xc208be2480, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:594 +0x9c7
github.com/gopherjs/gopherjs/compiler.func·021()
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:340 +0x4c
github.com/gopherjs/gopherjs/compiler.func·016(0xc208d23770, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:230 +0xa7
github.com/gopherjs/gopherjs/compiler.Compile(0x97bc50, 0x4, 0xc2080a3120, 0x4, 0x4, 0xc2080a1100, 0xc20802b310, 0x7f2007262a00, 0xc2080a0f40, 0x0, ...)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:341 +0x4ee8
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc20801f020, 0xc2080a80f0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/build/build.go:459 +0xf50
github.com/gopherjs/gopherjs/build.(*Session).BuildDir(0xc20801f020, 0xc20807e7b0, 0x2a, 0xc20807e7b0, 0x2a, 0x0, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/build/build.go:305 +0x1c9
main.func·001(0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/tool.go:80 +0xcc
main.handleError(0xc2094b3bc8, 0xc20802df00, 0x0, 0x1)
	/Go/src/github.com/gopherjs/gopherjs/tool.go:572 +0x2f
main.func·002(0xc208036820, 0xc20802b2e0, 0x0, 0x1)
	/Go/src/github.com/gopherjs/gopherjs/tool.go:128 +0x156
github.com/spf13/cobra.(*Command).execute(0xc208036820, 0xc20802b2b0, 0x1, 0x1, 0x0, 0x0)
	/Go/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0xc208037380, 0x0, 0x0)
	/Go/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
	/Go/src/github.com/gopherjs/gopherjs/tool.go:450 +0x1696
```

**Comment by Splizard** [comment]
Modifying the line to check if nil still panics
```
case *ast.SelectorExpr:
		sel, ok := c.p.Selections[e]
		if !ok || sel == nil { //Added || sel == nil
			// qualified identifier
			return c.formatExpr("%s", c.objectName(obj))
		}

		switch sel.Kind() { //This is where it originally panics
```

**Comment by neelance** [comment]
Thanks for reporting! Could you track down the piece of code that causes the panic when you try to compile it?

**Comment by Splizard** [comment]
This seems to cause it...
```
import "game"

func main() {
    game.Score++
}
```
game being a library which has in this case a float32 variable called "Score"

It's fixed by 
```
import "game"

func main() {
    game.Score = game.Score + 1
}
```

**Comment by shurcooL** [comment]
I can reproduce.
