### ISSUE TITLE
Panic when passing a pointer of a variable from another package to a function

### ISSUE THREAD

**Issue by Splizard** [gopherjs/gopherjs#245]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x593b5e]

goroutine 1 [running]:
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateSelection(0xc208791a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:135 +0xb9e
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateAssign(0xc208791a20, 0x7f79f1bf4ad0, 0xc2089b7f60, 0x96bc70, 0x2, 0x7f79f1bf96d0, 0xc209391360, 0xc209b6f800, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:766 +0x1d30
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc208791a20, 0x7f79f1bf4d00, 0xc2080afda0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:220 +0x7c09
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateImplicitConversion(0xc208791a20, 0x7f79f1bf4d00, 0xc2080afda0, 0x7f79f1bf3de8, 0xc208f23ea0, 0x2)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1102 +0xab3
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateArgs(0xc208791a20, 0xc2086c66c0, 0xc2080afde0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:115 +0x11b9
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateCall(0xc208791a20, 0xc20809ae00, 0xc2086c66c0, 0xc2089b7f00, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:744 +0x98
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc208791a20, 0x7f79f1bf4bb0, 0xc20809ae00, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:562 +0x13f4a
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc208791a20, 0x7f79f1bf4c58, 0xc2080b2870, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:426 +0xd843
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmtList(0xc208791a20, 0xc20809af40, 0x4, 0x4)
	/Go/src/github.com/gopherjs/gopherjs/compiler/statements.go:24 +0xa1
github.com/gopherjs/gopherjs/compiler.func·029()
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:667 +0x974
github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc208791a20, 0x1, 0xc2095eb9c8, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:64 +0x9f
github.com/gopherjs/gopherjs/compiler.translateFunction(0xc2080affe0, 0x0, 0x0, 0x0, 0xc2080b0930, 0xc208790f20, 0xc2084d0210, 0xc2093a88a0, 0xc2080b275c, 0x4, ...)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:668 +0x6ef
github.com/gopherjs/gopherjs/compiler.func·028(0xc2080b275c, 0x4, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:565 +0xf07
github.com/gopherjs/gopherjs/compiler.(*funcContext).translateToplevelFunction(0xc208790f20, 0xc2080b0960, 0xc2093a88a0, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:574 +0x3de
github.com/gopherjs/gopherjs/compiler.func·021()
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:340 +0x4c
github.com/gopherjs/gopherjs/compiler.func·016(0xc208772330, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:230 +0xa7
github.com/gopherjs/gopherjs/compiler.Compile(0x97b990, 0x4, 0xc20809d1e0, 0x4, 0x4, 0xc20809acc0, 0xc20802b310, 0x7f79f1bf4900, 0xc20809ab00, 0x0, ...)
	/Go/src/github.com/gopherjs/gopherjs/compiler/package.go:341 +0x4edf
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc20801f020, 0xc208098a00, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/build/build.go:459 +0xf50
github.com/gopherjs/gopherjs/build.(*Session).BuildDir(0xc20801f020, 0xc2080767b0, 0x2a, 0xc2080767b0, 0x2a, 0x0, 0x0, 0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/build/build.go:305 +0x1c9
main.func·001(0x0, 0x0)
	/Go/src/github.com/gopherjs/gopherjs/tool.go:80 +0xcc
main.handleError(0xc2095edbc8, 0xc20802d8c0, 0x0, 0x1)
	/Go/src/github.com/gopherjs/gopherjs/tool.go:573 +0x2f
main.func·002(0xc208036820, 0xc20802b2e0, 0x0, 0x1)
	/Go/src/github.com/gopherjs/gopherjs/tool.go:128 +0x156
github.com/spf13/cobra.(*Command).execute(0xc208036820, 0xc20802b2b0, 0x1, 0x1, 0x0, 0x0)
	/Go/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0xc208037520, 0x0, 0x0)
	/Go/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
	/Go/src/github.com/gopherjs/gopherjs/tool.go:451 +0x16c4
```

Crash occurs from this:
```
package main

import "game"
import "tracker"

func main() {
    tracker.Track(&game.Score) //Commenting out this line in the program will stop the panic.
    //More code here...
}
```

**Comment by neelance** [comment]
Wow, you're really tracking down those cross-package bugs. Thanks! ;-)
