### ISSUE TITLE
interface conversion: interface is []interface {}, not js.S

### ISSUE THREAD

**Issue by spamguy** [gopherjs/gopherjs#336]
Caveat: I am Golang-blind. Bear with me!

I am modifying an existing Golang library to tie into my JavaScript with GopherJS.

I added this function to the class Variant:

```
func New(o *js.Object) *Variant {
	return &Variant{
		Name: o.Get("name").String(),
		Graph: graph.New(o.Get("regions").Interface().([]interface {})),
	}
}
```

And this function to the class Graph:

```
func New(regions []interface{}) *Graph {
	return &Graph{
	}
}
```

Now, let's say I call `global.variant.New({ name: 'X', regions: [] })` in JavaScript. I hit this error:

```
Uncaught Error: interface conversion: interface is []interface {}, not js.S
      at $callDeferred (judge.js:1372:17)
      at $panic (judge.js:1411:3)
      at $assertType (judge.js:1131:5)
      at $packages.github.com/spamguy/godip/variant.New (judge.js:22891:118)
      at Object.v.$externalizeWrapper [as New] (judge.js:1815:24)
      at LineStream.<anonymous> (test/datc.spec.js:101:38)
      at readableAddChunk (_stream_readable.js:163:16)
      at LineStream.Readable.push (_stream_readable.js:126:10)
      at LineStream.Transform.push (_stream_transform.js:140:32)
      at LineStream._pushBuffer (node_modules/byline/lib/byline.js:123:17)
      at LineStream._transform (node_modules/byline/lib/byline.js:114:8)
      at LineStream.Transform._read (_stream_transform.js:179:10)
      at LineStream.Transform._write (_stream_transform.js:167:12)
      at doWrite (_stream_writable.js:301:12)
      at writeOrBuffer (_stream_writable.js:288:5)
      at LineStream.Writable.write (_stream_writable.js:217:11)
      at ReadStream.ondata (_stream_readable.js:540:20)
      at readableAddChunk (_stream_readable.js:163:16)
      at ReadStream.Readable.push (_stream_readable.js:126:10)
      at onread (fs.js:1679:12)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
```

According to the docs, I thought js.S was shorthand for []interface{}. Shouldn't they equate? The point is moot, though: I stick to longhand in this code and don't use js.S anywhere, so this error shouldn't even be happening.

If you need the full code, pre- and post-compilation, see https://github.com/spamguy/diplomacy-godip .

**Comment by spamguy** [comment]
Disregard, I was building off the wrong copy of Golang code.
