### ISSUE TITLE
refVal.Convert() does not work with booleans

### ISSUE THREAD

**Issue by PSG-Luna** [gopherjs/gopherjs#375]
The following code sample works in the Go playground, but fails with gopherJS, it involves the conversion of bools:

```Go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	b := true
	b2 := false

	refVal := reflect.ValueOf(&b).Elem()
	refVal.Set(reflect.ValueOf(b2).Convert(refVal.Type()))

	fmt.Printf("%v", b)
}
```

**Comment by shurcooL** [comment]
Thanks. I can reproduce:

```
$ gopherjs run main.go 
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
src/github.com/shurcooL/play/31/main.go.783455304:1473
      throw err;
      ^

Error: reflect: call of reflect.Convert on bool Value
    at $callDeferred (src/github.com/shurcooL/play/31/main.go.783455304:1404:17)
    at $panic (src/github.com/shurcooL/play/31/main.go.783455304:1443:3)
    at $packages.reflect.cvtDirect (src/github.com/shurcooL/play/31/main.go.783455304:10531:4)
    at $packages.reflect.Value.ptr.Convert (src/github.com/shurcooL/play/31/main.go.783455304:13226:10)
    at $packages.main.main (src/github.com/shurcooL/play/31/main.go.783455304:16368:15)
    at $packages.main.$init (src/github.com/shurcooL/play/31/main.go.783455304:16382:9)
    at $goroutine (src/github.com/shurcooL/play/31/main.go.783455304:1463:19)
    at $schedule (src/github.com/shurcooL/play/31/main.go.783455304:1517:5)
    at $go (src/github.com/shurcooL/play/31/main.go.783455304:1493:3)
    at Object.<anonymous> (src/github.com/shurcooL/play/31/main.go.783455304:16392:1)
    at Object.<anonymous> (src/github.com/shurcooL/play/31/main.go.783455304:16395:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

Does `Convert` work on other types and fail on bool only, or does it fail for all types?

I just tried, it seems to work for `int` -> `int`, so this might be `bool`-specific then.

**Comment by shurcooL** [comment]
Could the fix be just this?

```diff
diff --git a/compiler/natives/reflect/reflect.go b/compiler/natives/reflect/reflect.go
index cf4f513..1788368 100644
--- a/compiler/natives/reflect/reflect.go
+++ b/compiler/natives/reflect/reflect.go
@@ -452,7 +452,7 @@ func cvtDirect(v Value, typ Type) Value {
 	case Struct:
 		val = jsType(typ).Get("ptr").New()
 		copyStruct(val, srcVal, typ)
-	case Array, Func, Interface, Map, String:
+	case Array, Func, Interface, Map, String, Bool:
 		val = js.InternalObject(v.ptr)
 	default:
 		panic(&ValueError{"reflect.Convert", k})
```

I tried it and it _seemed_ to work:

```
31 $ gopherjs run main.go 
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
false
31 $ go run main.go 
false
31 $ open main.go # Changed b2 to true.
31 $ go run main.go 
true
31 $ gopherjs run main.go 
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
true
```
