### ISSUE TITLE
panic with packages not found (was: PR #409)

### ISSUE THREAD

**Issue by tgulacsi** [gopherjs/gopherjs#410]
```
:tgulacsi@tgulacsi-Aspire-V3-371: ~/src/github.com/influx6/govfx/examples/shadowDOM
! go install github.com/gopherjs/gopherjs && gopherjs build app.go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x6996c4]

goroutine 1 [running]:
panic(0x9fd720, 0xc82000e190)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
go/types.(*Checker).handleBailout(0xc82011c000, 0xc8217c9dd0)
        /usr/local/go/src/go/types/check.go:213 +0xd8
panic(0x9fd720, 0xc82000e190)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
go/types.(*Checker).handleBailout(0xc820f68460, 0xc8217c7908)
        /usr/local/go/src/go/types/check.go:213 +0xd8
panic(0x9fd720, 0xc82000e190)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/gopherjs/gopherjs/compiler.packageImporter.Import(0xc82143e9d0, 0xc82143e9e0, 0xc8214d9721, 0x18, 0xa32c20, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/compiler/package.go:117 +0x124
github.com/gopherjs/gopherjs/compiler.(*packageImporter).Import(0xc82143ea00, 0xc8214d9721, 0x18, 0xc8217c7590, 0x0, 0x0)
        <autogenerated>:22 +0xb8
go/types.(*Checker).collectObjects(0xc820f68460)
        /usr/local/go/src/go/types/resolver.go:196 +0x3354
go/types.(*Checker).Files(0xc820f68460, 0xc82142f9a0, 0x3, 0x4, 0x0, 0x0)
        /usr/local/go/src/go/types/check.go:223 +0xb3
go/types.(*Config).Check(0xc820837480, 0xc8200f2a81, 0x22, 0xc820e07c00, 0xc82142f9a0, 0x3, 0x4, 0xc82126c280, 0x41d567, 0x0, ...)
        /usr/local/go/src/go/types/api.go:344 +0x1f7
github.com/gopherjs/gopherjs/compiler.Compile(0xc8200f2a81, 0x22, 0xc82142f9a0, 0x3, 0x4, 0xc820e07c00, 0xc82143e9d0, 0x0, 0x4, 0x0, ...)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/compiler/package.go:147 +0x54c
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc8200fc340, 0xc820be3ae0, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:512 +0x10f6
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc8200fc340, 0xc8200f2a81, 0x22, 0xc8200fa1c0, 0x3e, 0x0, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:414 +0x219
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage.func1(0xc8200f2a81, 0x22, 0xc8200f2a81, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:509 +0x5a
github.com/gopherjs/gopherjs/compiler.packageImporter.Import(0xc8200f0a10, 0xc8200f0a20, 0xc8200f2a81, 0x22, 0xa32c20, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/compiler/package.go:108 +0xa2
github.com/gopherjs/gopherjs/compiler.(*packageImporter).Import(0xc8200f0a40, 0xc8200f2a81, 0x22, 0xc820cb7a58, 0x0, 0x0)
        <autogenerated>:22 +0xb8
go/types.(*Checker).collectObjects(0xc82011c000)
        /usr/local/go/src/go/types/resolver.go:196 +0x3354
go/types.(*Checker).Files(0xc82011c000, 0xc8200f8078, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/go/types/check.go:223 +0xb3
go/types.(*Config).Check(0xc8200faac0, 0xababa0, 0x4, 0xc8200fa340, 0xc8200f8078, 0x1, 0x1, 0xc8200f6730, 0x0, 0x0, ...)
        /usr/local/go/src/go/types/api.go:344 +0x1f7
github.com/gopherjs/gopherjs/compiler.Compile(0xababa0, 0x4, 0xc8200f8078, 0x1, 0x1, 0xc8200fa340, 0xc8200f0a10, 0x0, 0x902ec0, 0x0, ...)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/compiler/package.go:147 +0x54c
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc8200fc340, 0xc8200f60a0, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:512 +0x10f6
github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc8200fc340, 0xc8200f0360, 0x1, 0x1, 0xc8200f0370, 0x6, 0xc8200fa1c0, 0x3e, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:388 +0x2cb
main.main.func1.1(0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:112 +0xb7e
main.handleError(0xc8217cbad8, 0xc8200fa240, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:653 +0x3f
main.main.func1(0xc820106000, 0xc8200f0360, 0x1, 0x1)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:89 +0x108
github.com/spf13/cobra.(*Command).execute(0xc820106000, 0xc8200f0310, 0x1, 0x1, 0x0, 0x0)
        /home/tgulacsi/src/github.com/spf13/cobra/command.go:569 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc820106e00, 0xc820106000, 0x0, 0x0)
        /home/tgulacsi/src/github.com/spf13/cobra/command.go:656 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xc820106e00, 0x0, 0x0)
        /home/tgulacsi/src/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:505 +0x161f
```

**Comment by tgulacsi** [comment]
```
!git diff
diff --git a/build/build.go b/build/build.go
index 612e2d1..f822b83 100644
--- a/build/build.go
+++ b/build/build.go
@@ -400,6 +400,9 @@ func (s *Session) BuildImportPath(path string) (*compiler.Archive, error) {

 func (s *Session) buildImportPathWithSrcDir(path string, srcDir string) (*compiler.Archive, error) {
        if pkg, found := s.Packages[path]; found {
+               if pkg.Archive == nil {
+                       panic(fmt.Sprintf("%q => %#v", path, pkg.Archive))
+               }
                return pkg.Archive, nil
        }

@@ -410,10 +413,13 @@ func (s *Session) buildImportPathWithSrcDir(path string, srcDir string) (*compil
        if err != nil {
                return nil, err
        }
-
        if err := s.BuildPackage(pkg); err != nil {
                return nil, err
        }
+       if pkg.Archive == nil {
+               panic(fmt.Sprintf("%q + %q => %#v", path, srcDir, pkg.Archive))
+       }
+
        return pkg.Archive, nil
 }
```

```
:tgulacsi@tgulacsi-Aspire-V3-371: ~/src/github.com/influx6/govfx/examples/shadowDOM
! go install github.com/gopherjs/gopherjs && gopherjs build app.go
panic: "github.com/influx6/govfx" => (*compiler.Archive)(nil) [recovered]
        panic: "github.com/influx6/govfx" => (*compiler.Archive)(nil)

goroutine 1 [running]:
panic(0x908940, 0xc8204fedd0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
go/types.(*Checker).handleBailout(0xc82011c000, 0xc820bbfdd0)
        /usr/local/go/src/go/types/check.go:213 +0xd8
panic(0x908940, 0xc8204fedd0)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc8200f63a0, 0xc8210df3c1, 0x18, 0x0, 0x0, 0xc820bbeb98, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:404 +0x25b
github.com/gopherjs/gopherjs/build.(*Session).BuildImportPath(0xc8200f63a0, 0xc8210df3c1, 0x18, 0x7, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:398 +0x4d
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc8200f63a0, 0xc821861ea0, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:463 +0x2033
github.com/gopherjs/gopherjs/build.(*Session).buildImportPathWithSrcDir(0xc8200f63a0, 0xc8200eef91, 0x22, 0xc8200f8280, 0x3e, 0x0, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:416 +0x408
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage.func1(0xc8200eef91, 0x22, 0xc8200eef91, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:515 +0x5a
github.com/gopherjs/gopherjs/compiler.packageImporter.Import(0xc8200f0b20, 0xc8200f0b30, 0xc8200eef91, 0x22, 0xa32c20, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/compiler/package.go:108 +0xa2
github.com/gopherjs/gopherjs/compiler.(*packageImporter).Import(0xc8200f0b50, 0xc8200eef91, 0x22, 0xc820bbfa58, 0x0, 0x0)
        <autogenerated>:22 +0xb8
go/types.(*Checker).collectObjects(0xc82011c000)
        /usr/local/go/src/go/types/resolver.go:196 +0x3354
go/types.(*Checker).Files(0xc82011c000, 0xc8200f40a8, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/go/types/check.go:223 +0xb3
go/types.(*Config).Check(0xc8200f8b80, 0xababa0, 0x4, 0xc8200f8400, 0xc8200f40a8, 0x1, 0x1, 0xc8200f2910, 0x0, 0x0, ...)
        /usr/local/go/src/go/types/api.go:344 +0x1f7
github.com/gopherjs/gopherjs/compiler.Compile(0xababa0, 0x4, 0xc8200f40a8, 0x1, 0x1, 0xc8200f8400, 0xc8200f0b20, 0x0, 0x902ec0, 0x0, ...)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/compiler/package.go:147 +0x54c
github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc8200f63a0, 0xc8200f2280, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:518 +0x10f6
github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc8200f63a0, 0xc8200f0470, 0x1, 0x1, 0xc8200f0480, 0x6, 0xc8200f8280, 0x3e, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/build/build.go:388 +0x2cb
main.main.func1.1(0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:112 +0xb7e
main.handleError(0xc820bc1ad8, 0xc8200f8300, 0x0, 0x0)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:653 +0x3f
main.main.func1(0xc820106000, 0xc8200f0470, 0x1, 0x1)
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:89 +0x108
github.com/spf13/cobra.(*Command).execute(0xc820106000, 0xc8200f0420, 0x1, 0x1, 0x0, 0x0)
        /home/tgulacsi/src/github.com/spf13/cobra/command.go:569 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0xc820106e00, 0xc820106000, 0x0, 0x0)
        /home/tgulacsi/src/github.com/spf13/cobra/command.go:656 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xc820106e00, 0x0, 0x0)
        /home/tgulacsi/src/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
        /home/tgulacsi/src/github.com/gopherjs/gopherjs/tool.go:505 +0x161f
```

**Comment by neelance** [comment]
@tgulacsi Could you please check if the newest changed of #411 have solved this issue for you?

**Comment by neelance** [comment]
@tgulacsi confirmed on #409. Closing.
