### ISSUE TITLE
os.Open always fails on Node.js on Mac OS X

### ISSUE THREAD

**Issue by hajimehoshi** [gopherjs/gopherjs#416]
```go:file.go
package main

import (
        "os"
)

func main() {
        _, err := os.Open("foo.txt")
        if err != nil {
                panic(err)
        }
}
```

This fails on Mac OS X with this error:

```sh
$ gopherjs run file.go                                                                                                                                                                                      
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md

/Users/hajimehoshi/test/file.go.708533707:1472
        throw err;
              ^
Error: open foo.txt: permission denied
    at $callDeferred (/Users/hajimehoshi/test/file.go.708533707:1404:17)
    at $panic (/Users/hajimehoshi/test/file.go.708533707:1443:3)
    at $packages.main.main (/Users/hajimehoshi/test/file.go.708533707:7711:4)
    at $packages.main.$init (/Users/hajimehoshi/test/file.go.708533707:7719:4)
    at $goroutine (/Users/hajimehoshi/test/file.go.708533707:1463:19)
    at $schedule (/Users/hajimehoshi/test/file.go.708533707:1520:5)
    at $go (/Users/hajimehoshi/test/file.go.708533707:1496:3)
    at Object.<anonymous> (/Users/hajimehoshi/test/file.go.708533707:7730:1)
    at Object.<anonymous> (/Users/hajimehoshi/test/file.go.708533707:7733:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

even though the file 'foo.txt' exists.

**Comment by shurcooL** [comment]
Have you noticed this line in the output?

```
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
```

You need to follow the steps described there to add support for `os.Open` and the like for Node.

I confirmed that it works once that module is installed.

```bash
$ touch foo.txt
$ go run foo.go 
$ gopherjs run foo.go 
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
$ 
```

**Comment by hajimehoshi** [comment]
Ah, thanks. Building cd node-gyp fails on my machine BTW, but I think this is not related to GopherJS.
