### ISSUE TITLE
Gopherjs build allocating a lot of memory

### ISSUE THREAD

**Issue by aashishthite** [gopherjs/gopherjs#456]
Hey Guys, I am trying to migrate my golang project from using older Godeps to vendor/. When I try to `gopherjs build` the gopherjs build process seems to be allocating a lot of memory. gopherjs works fine with older style of Godeps.  Here is the traceback that I see

```
20:40:13 fatal error: runtime: out of memory

20:40:13 runtime stack:
20:40:13 runtime.throw(0xb3da50, 0x16)
20:40:13    /usr/local/go/src/runtime/panic.go:547 +0x90
20:40:13 runtime.sysMap(0xce35e50000, 0x358340000, 0x0, 0xe056b8)
20:40:13    /usr/local/go/src/runtime/mem_linux.go:206 +0x9b
20:40:13 runtime.(*mheap).sysAlloc(0xdeadc0, 0x358340000, 0x2)
20:40:13    /usr/local/go/src/runtime/malloc.go:429 +0x191
20:40:13 runtime.(*mheap).grow(0xdeadc0, 0x1ac1a0, 0x0)
20:40:13    /usr/local/go/src/runtime/mheap.go:651 +0x63
20:40:13 runtime.(*mheap).allocSpanLocked(0xdeadc0, 0x1ac19a, 0x7f4eb02c9b58)
20:40:13    /usr/local/go/src/runtime/mheap.go:553 +0x4f6
20:40:13 runtime.(*mheap).alloc_m(0xdeadc0, 0x1ac19a, 0xffffff0100000000, 0x7f4eaaffcdd0)
20:40:13    /usr/local/go/src/runtime/mheap.go:437 +0x119
20:40:13 runtime.(*mheap).alloc.func1()
20:40:13    /usr/local/go/src/runtime/mheap.go:502 +0x41
20:40:13 runtime.systemstack(0x7f4eaaffcde8)
20:40:13    /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
20:40:13 runtime.(*mheap).alloc(0xdeadc0, 0x1ac19a, 0x10100000000, 0xc820000180)
20:40:13    /usr/local/go/src/runtime/mheap.go:503 +0x63
20:40:13 runtime.largeAlloc(0x358334000, 0xc800000000, 0x1)
20:40:13    /usr/local/go/src/runtime/malloc.go:766 +0xb3
20:40:13 runtime.mallocgc.func3()
20:40:13    /usr/local/go/src/runtime/malloc.go:664 +0x33
20:40:13 runtime.systemstack(0xc820022000)
20:40:13    /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
20:40:13 runtime.mstart()
20:40:13    /usr/local/go/src/runtime/proc.go:1051
20:40:13 
20:40:13 goroutine 1 [running]:
20:40:13 runtime.systemstack_switch()
20:40:13    /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc824bff838 sp=0xc824bff830
20:40:13 runtime.mallocgc(0x358334000, 0x91ae20, 0x0, 0xc8212874b0)
20:40:13    /usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc824bff910 sp=0xc824bff838
20:40:13 runtime.newarray(0x91ae20, 0x35833400, 0x6)
20:40:13    /usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc824bff950 sp=0xc824bff910
20:40:13 runtime.growslice(0x905f00, 0xca48bcc000, 0x2acf5c00, 0x2acf5c00, 0x2acf5c01, 0x0, 0x0, 0x0)
20:40:13    /usr/local/go/src/runtime/slice.go:100 +0x2c1 fp=0xc824bff9c0 sp=0xc824bff950
20:40:13 github.com/gopherjs/gopherjs/compiler.(*funcContext).translateSelection(0xc8202208f0, 0x7f4eb2d71820, 0xc822c5c780, 0xdd, 0x0, 0x0, 0x0, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/utils.go:145 +0xb03 fp=0xc824bffc40 sp=0xc824bff9c0
20:40:13 github.com/gopherjs/gopherjs/compiler.(*funcContext).translateExpr(0xc8202208f0, 0x7f4eb2d68330, 0xc820731de0, 0xddcbe0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:516 +0x1bba0 fp=0xc824c01610 sp=0xc824bffc40
20:40:13 github.com/gopherjs/gopherjs/compiler.(*funcContext).translateImplicitConversion(0xc8202208f0, 0x7f4eb2d68330, 0xc820731de0, 0x7f4eb2dac328, 0xddcbe0, 0xc820d87ad0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/expressions.go:1118 +0x104 fp=0xc824c01720 sp=0xc824c01610
20:40:13 github.com/gopherjs/gopherjs/compiler.(*funcContext).translateAssign(0xc8202208f0, 0x7f4eb2d682f8, 0xc8221d89a0, 0x7f4eb2d68330, 0xc820731de0, 0xc82242b101, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/statements.go:683 +0xc6c fp=0xc824c01d58 sp=0xc824c01720
20:40:13 github.com/gopherjs/gopherjs/compiler.(*funcContext).translateStmt(0xc8202208f0, 0x7f4eb2d68528, 0xc82242b180, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/statements.go:367 +0xfe5a fp=0xc824c03b40 sp=0xc824c01d58
20:40:13 github.com/gopherjs/gopherjs/compiler.Compile.func6.1()
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/package.go:337 +0x174 fp=0xc824c03bb0 sp=0xc824c03b40
20:40:13 github.com/gopherjs/gopherjs/compiler.(*funcContext).CatchOutput(0xc8202208f0, 0x1, 0xc824c03ca8, 0x0, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/utils.go:65 +0x84 fp=0xc824c03bf8 sp=0xc824c03bb0
20:40:13 github.com/gopherjs/gopherjs/compiler.Compile.func6()
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/package.go:338 +0x95 fp=0xc824c03ce0 sp=0xc824c03bf8
20:40:13 github.com/gopherjs/gopherjs/compiler.Compile.func4(0xc82242b140, 0x0, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/package.go:283 +0xa9 fp=0xc824c03e00 sp=0xc824c03ce0
20:40:13 github.com/gopherjs/gopherjs/compiler.Compile(0xacefb0, 0x4, 0xc82011a148, 0x1, 0x1, 0xc82011c200, 0xc820153440, 0x0, 0x0, 0x0, ...)
20:40:13    /go/src/github.com/gopherjs/gopherjs/compiler/package.go:340 +0x3cad fp=0xc824c05100 sp=0xc824c03e00
20:40:13 github.com/gopherjs/gopherjs/build.(*Session).BuildPackage(0xc82011e3a0, 0xc820118050, 0x0, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/build/build.go:523 +0x1189 fp=0xc824c05680 sp=0xc824c05100
20:40:13 github.com/gopherjs/gopherjs/build.(*Session).BuildFiles(0xc82011e3a0, 0xc820116810, 0x1, 0x3, 0x7ffe8bfd6d49, 0x17, 0xc8201161e0, 0x24, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/build/build.go:390 +0x2cb fp=0xc824c05788 sp=0xc824c05680
20:40:13 main.main.func1.1(0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/tool.go:112 +0xc14 fp=0xc824c059a0 sp=0xc824c05788
20:40:13 main.handleError(0xc824c05ae8, 0xc82011c080, 0x0, 0x0)
20:40:13    /go/src/github.com/gopherjs/gopherjs/tool.go:697 +0x3f fp=0xc824c05a90 sp=0xc824c059a0
20:40:13 main.main.func1(0xc82012a000, 0xc820116810, 0x1, 0x3)
20:40:13    /go/src/github.com/gopherjs/gopherjs/tool.go:89 +0x14d fp=0xc824c05b28 sp=0xc824c05a90
20:40:13 github.com/spf13/cobra.(*Command).execute(0xc82012a000, 0xc820116660, 0x3, 0x3, 0x0, 0x0)
20:40:13    /go/src/github.com/spf13/cobra/command.go:565 +0x85a fp=0xc824c05c40 sp=0xc824c05b28
20:40:13 github.com/spf13/cobra.(*Command).ExecuteC(0xc82012ae00, 0xc82012a000, 0x0, 0x0)
20:40:13    /go/src/github.com/spf13/cobra/command.go:651 +0x55c fp=0xc824c05d50 sp=0xc824c05c40
20:40:13 github.com/spf13/cobra.(*Command).Execute(0xc82012ae00, 0x0, 0x0)
20:40:13    /go/src/github.com/spf13/cobra/command.go:610 +0x2d fp=0xc824c05d78 sp=0xc824c05d50
20:40:13 main.main()
20:40:13    /go/src/github.com/gopherjs/gopherjs/tool.go:537 +0x1602 fp=0xc824c05f20 sp=0xc824c05d78
20:40:13 runtime.main()
20:40:13    /usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc824c05f70 sp=0xc824c05f20
20:40:13 runtime.goexit()
20:40:13    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc824c05f78 sp=0xc824c05f70
20:40:13 
20:40:13 goroutine 17 [syscall, 5 minutes, locked to thread]:
20:40:13 runtime.goexit()
20:40:13    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by shurcooL** [comment]
Is this a public Go project that we can reproduce this on?

**Comment by aashishthite** [comment]
Hi Dimitri,
Unfortunately this is not a public project.
I'd be happy to help test against my project.
Thanks for responding,
Aashish

On Monday, May 9, 2016, Dmitri Shuralyov <notifications@github.com> wrote:

> Is this a public Go project that we can reproduce this on?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gopherjs/gopherjs/issues/456#issuecomment-218058057>
>


-- 
Sent from a typo-prone iPhone

**Comment by neelance** [comment]
Sorry, but I need some way to reproduce this.
