### ISSUE TITLE
Proposal: Implement `js` package with friendlier panics on unsupported architectures.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs#542]
Right now, the [`github.com/gopherjs/gopherjs/js` package](https://godoc.org/github.com/gopherjs/gopherjs/js) is officially only implemented for [`js` architecture](https://github.com/gopherjs/gopherjs#architecture). That's where using it is meaningful, as:

> Calls to these functions are treated specially by GopherJS and translated directly to their corresponding JavaScript syntax.

However, in reality, it is also currently implemented for all other architectures. The implementation panics for most things with unfriendly messages, such as "invalid memory address or nil pointer dereference".

This means someone who tries to run Go code that (directly or indirectly) uses `js` package under an unsupported architecture will likely see an unfriendly panic, such as:

```
todomvc $ go run example.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x744f2]

goroutine 1 [running]:
panic(0xcaa20, 0xc42000a090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0xe66bf, 0xc, 0xf3788)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/js/js.go:32 +0x22
main.attachLocalStorage()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/vecty/examples/todomvc/example.go:39 +0x7c
main.main()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/vecty/examples/todomvc/example.go:17 +0x26
exit status 2
```

**I propose we change implementation of `github.com/gopherjs/gopherjs/js` for unsupported architectures (everything other than `js`) such that it panics with friendly error messages.** For example:

```
$ go run example.go 
panic: js.Object.Get is only implemented on js architecture, it's not implemented on amd64 architecture

goroutine 1 [running]:
panic(0xc9340, 0xc42000a350)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0xe6764, 0xc, 0xf38a8)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/js/unimplemented.go:13 +0xe4
main.attachLocalStorage()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/vecty/examples/todomvc/example.go:39 +0x7c
main.main()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/vecty/examples/todomvc/example.go:17 +0x26
exit status 2
```

I think that's a good thing to do, and it should help people less familiar with GopherJS understand what's going on.

This idea is inspired by previous experiences and, most recently, by https://github.com/gopherjs/vecty/issues/61. /cc @campoy

### Implementation Discussion

In my prototype, I simply added `// +build js` constraint to [`js.go` file](https://github.com/gopherjs/gopherjs/blob/master/js/js.go), and created a second file `unimplemented.go` that looks like this:

```Go
// +build !js

package js

import (
	"fmt"
	"runtime"
)

type Object struct{ object *Object }

func (o *Object) Get(key string) *Object {
	panic(fmt.Errorf("js.Object.Get is only implemented on js architecture, it's not implemented on %s architecture", runtime.GOARCH))
}

// ...
```

However, the challenging part of the implementation is dealing with `godoc`. When doing the above, it causes godoc of `github.com/gopherjs/gopherjs/js` package to show up without any documentation, because the `amd64` architecture has higher priority over `js`.

I can think of a couple alternative solutions, but so far I'm not sure what's the best one.

Before I spend more time thinking about this, I wanted to make the proposal to see what @neelance thinks.

**Comment by flimzy** [comment]
I'm not sure how directly this relates, but as it's related, I thought I'd bring it up to consider including in the discussion.

I think the problem extends beyond just the 'gopherjs/js' package. As a matter of best practice, how should js-only packages be structured?  I had a similar issue on one of my GopherJS bindings packages (see https://github.com/flimzy/go-pouchdb/issues/25), and also with the `jsbuiltins` package (see https://github.com/gopherjs/jsbuiltin/pull/9).

One solution is just to remove the `js` build tag. This makes most Go tools happy, up until compile time. This seems dirty to me, but it is pragmatic, and "mostly works" for most of these packages.

**Comment by slimsag** [comment]
FWIW I like the idea of making this more clear quite a lot.

As for the actual implementation, it's hard for me to say. But I would lean towards panics that perhaps are more direct (`js.Object.Get is only implemented on js architecture, perhaps you meant to run this project using GopherJS?`)

**Comment by alkchr** [comment]
Gday,

I am not familiar with how GopherJS is implemented. But I'm curious whether `js.Object` can be turned into an `interface` so it would be possible to implement it to use the code on any architecture. And GopherJS could still replace it by whatever JS representation it needs.

**Comment by shurcooL** [comment]
@neelance, how do you feel about this?

@alkchr, GopherJS started out with `Object` being an `interface{}` originally. However, it made the change from that to pointer to `struct{}`, because it was a better representation. See https://github.com/gopherjs/gopherjs/commit/0853187ab4154e73cf6f7bd43625ab83e762a000#diff-37afcbb71b3321eb845150243b012cec.

**Comment by slimsag** [comment]
FYI, I have worked around this with https://github.com/gopherjs/vecty/commit/10e09b143553c2e498c08a6abcb3d9212ce61ff8
