### ISSUE TITLE
reflect.Value.ptr.MapKeys throws TypeError: dst.$set is not a function 

### ISSUE THREAD

**Issue by pbrown12303** [gopherjs/gopherjs#719]
During debugging I was trying to print the value of a struct containing a map from uuid.UUID (github.com/satori/go.uuid) to an interface and got this error, e.g.

`log.Printf("Element value: %v", el")`

where el is an interface whose current value is the indicated struct. Here's the stack dump:

```
jquery.js:3860 jQuery.Deferred exception: dst.$set is not a function TypeError: dst.$set is not a function
    at typedmemmove (http://localhost:8080/js/crlEditor.js:17398:7)
    at Object.$packages.reflect.Value.ptr.MapKeys (http://localhost:8080/js/crlEditor.js:19934:5)
    at Object.$packages.fmt.pp.ptr.printValue (http://localhost:8080/js/crlEditor.js:22452:37)
    at Object.$packages.fmt.pp.ptr.printValue (http://localhost:8080/js/crlEditor.js:22508:13)
    at Object.$packages.fmt.pp.ptr.printValue (http://localhost:8080/js/crlEditor.js:22628:15)
    at Object.$packages.fmt.pp.ptr.printArg (http://localhost:8080/js/crlEditor.js:22350:12)
    at Object.$packages.fmt.pp.ptr.doPrintf (http://localhost:8080/js/crlEditor.js:22854:15)
    at Object.Sprintf (http://localhost:8080/js/crlEditor.js:21636:10)
    at Object.Printf (http://localhost:8080/js/crlEditor.js:49614:12)
    at Object.$packages.github.com/pbrown12303/activeCRL/activeCRL/core.FunctionCallManager.ptr.AddFunctionCall (http://localhost:8080/js/crlEditor.js:53663:12)
    at queueFunctionExecutions (http://localhost:8080/js/crlEditor.js:51380:33)
    at postChange (http://localhost:8080/js/crlEditor.js:51424:8)
    at abstractionChanged (http://localhost:8080/js/crlEditor.js:51266:8)
    at childChanged (http://localhost:8080/js/crlEditor.js:51302:11)
    at notifyParent (http://localhost:8080/js/crlEditor.js:51337:9)
    at postChange (http://localhost:8080/js/crlEditor.js:51425:8)
    at Object.$packages.github.com/pbrown12303/activeCRL/activeCRL/core.elementPointer.ptr.SetElement (http://localhost:8080/js/crlEditor.js:52830:8)
    at Object.$packages.github.com/pbrown12303/activeCRL/activeCRL/core.refinement.ptr.SetRefinedElement (http://localhost:8080/js/crlEditor.js:55674:12)
    at ReplicateAsRefinement (http://localhost:8080/js/crlEditor.js:58831:22)
    at CreateReplicateAsRefinement (http://localhost:8080/js/crlEditor.js:58621:8)
    at Object.CreateReplicateAsRefinementFromUri (http://localhost:8080/js/crlEditor.js:58637:10)
    at NewTreeManager (http://localhost:8080/js/crlEditor.js:59760:13)
    at Object.NewCrlEditor (http://localhost:8080/js/crlEditor.js:59593:10)
    at initializeEditor (http://localhost:8080/js/crlEditor.js:60053:15)
    at v.$externalizeWrapper (http://localhost:8080/js/crlEditor.js:1867:24)
    at HTMLDocument.<anonymous> (http://localhost:8080/index/:20:3)
    at mightThrow (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js:3583:29)
    at process (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js:3651:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
jquery.js:3869 Uncaught TypeError: dst.$set is not a function
    at typedmemmove (reflect.go:487)
    at Object.$packages.reflect.Value.ptr.MapKeys (value.go:1107)
    at Object.$packages.fmt.pp.ptr.printValue (print.go:739)
    at Object.$packages.fmt.pp.ptr.printValue (print.go:776)
    at Object.$packages.fmt.pp.ptr.printValue (print.go:846)
    at Object.$packages.fmt.pp.ptr.printArg (print.go:682)
    at Object.$packages.fmt.pp.ptr.doPrintf (print.go:996)
    at Object.Sprintf (print.go:196)
    at Object.Printf (log.go:299)
    at Object.$packages.github.com/pbrown12303/activeCRL/activeCRL/core.FunctionCallManager.ptr.AddFunctionCall (FunctionCallManager.go:33)
    at queueFunctionExecutions (ChangeNotification.go:189)
    at postChange (ChangeNotification.go:227)
    at abstractionChanged (ChangeNotification.go:120)
    at childChanged (ChangeNotification.go:142)
    at notifyParent (ChangeNotification.go:165)
    at postChange (ChangeNotification.go:229)
    at Object.$packages.github.com/pbrown12303/activeCRL/activeCRL/core.elementPointer.ptr.SetElement (ElementPointer.go:304)
    at Object.$packages.github.com/pbrown12303/activeCRL/activeCRL/core.refinement.ptr.SetRefinedElement (Refinement.go:154)
    at ReplicateAsRefinement (Utilities.go:456)
    at CreateReplicateAsRefinement (Utilities.go:85)
    at Object.CreateReplicateAsRefinementFromUri (Utilities.go:94)
    at NewTreeManager (TreeManager.go:60)
    at Object.NewCrlEditor (CrlEditor.go:36)
    at initializeEditor (crlEditorJs.go:76)
    at v.$externalizeWrapper (crlEditor.js:1867)
    at HTMLDocument.<anonymous> ((index):20)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
typedmemmove @ reflect.go:487
$packages.reflect.Value.ptr.MapKeys @ value.go:1107
$packages.fmt.pp.ptr.printValue @ print.go:739
$packages.fmt.pp.ptr.printValue @ print.go:776
$packages.fmt.pp.ptr.printValue @ print.go:846
$packages.fmt.pp.ptr.printArg @ print.go:682
$packages.fmt.pp.ptr.doPrintf @ print.go:996
Sprintf @ print.go:196
Printf @ log.go:299
$packages.github.com/pbrown12303/activeCRL/activeCRL/core.FunctionCallManager.ptr.AddFunctionCall @ FunctionCallManager.go:33
queueFunctionExecutions @ ChangeNotification.go:189
postChange @ ChangeNotification.go:227
abstractionChanged @ ChangeNotification.go:120
childChanged @ ChangeNotification.go:142
notifyParent @ ChangeNotification.go:165
postChange @ ChangeNotification.go:229
$packages.github.com/pbrown12303/activeCRL/activeCRL/core.elementPointer.ptr.SetElement @ ElementPointer.go:304
$packages.github.com/pbrown12303/activeCRL/activeCRL/core.refinement.ptr.SetRefinedElement @ Refinement.go:154
ReplicateAsRefinement @ Utilities.go:456
CreateReplicateAsRefinement @ Utilities.go:85
CreateReplicateAsRefinementFromUri @ Utilities.go:94
NewTreeManager @ TreeManager.go:60
NewCrlEditor @ CrlEditor.go:36
initializeEditor @ crlEditorJs.go:76
v.$externalizeWrapper @ crlEditor.js:1867
(anonymous) @ (index):20
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
jQuery.readyException @ jquery.js:3868
(anonymous) @ jquery.js:3888
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
process @ jquery.js:3671
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
```

**Comment by pbrown12303** [comment]
There appear to be some issues with the use of uuid.UUID values as index keys (see also issue #848). The workaround is to use the string value of the UUID as the key
