### ISSUE TITLE
Prepack - generate JS that can be processed by prepack.io

### ISSUE THREAD

**Issue by millergarym** [gopherjs/gopherjs#749]
This is an aspirational request. That is I have not idea how hard this is, but how ever complex I think it is, its probably more complex (even taking the previous statement into account).

Take a look at  https://prepack.io/. It has the promise of removing the bloat. eg from of the standard libraries.

However, even the simplest gopherjs'ed code doesn't pass muster. Two examples below.
Both examples use the following html.

```html
<!DOCTYPE html>
<html>
<body>
    <input id="newd-btn" type="button" value="+">
    <input id="name" type="textbox" value="load value">
    <script src="simple.js"></script> 
    <!-- <script src="simple-pp.js"></script>  -->
</body>
</html>
```

### Ex 1

The gopsherjs code works as expected. 
The prepack js logs to console and then throw an exception. That looks to me like a Go panic.

```
simple-pp.js:35 Uncaught 
__constructor {stack: "TypeError↵    at main (simple.js:1785:14)↵    at $…:2362:1↵    at call (native)↵    at simple.js:2:1", message: "null or undefined"}
message
:
"null or undefined"
stack
:
"TypeError↵    at main (simple.js:1785:14)↵    at $init (simple.js:2351:4)↵    at apply (native)↵    at $goroutine (simple.js:1471:15)↵    at $runScheduled (simple.js:1511:7)↵    at $schedule (simple.js:1527:5)↵    at $go (simple.js:1503:3)↵    at simple.js:2362:1↵    at call (native)↵    at simple.js:2:1"
__proto__
:
Error
```

To reproduce
```
go generate
prepack simple.js > simple-pp.js
```

``` go
// simple.go
package main

//go:generate gopherjs build simple.go -o simple.js

import (
	"github.com/gopherjs/gopherjs/js"
)

func main() {
	print("hw")
	js.Global.Get("newd-btn").Call("addEventListener", "click", func(e *js.Object) {
		print("this is an ", e)
	})
	o := js.Global.Get("document")
	btn := o.Call("getElementById", "newd-btn")
	btn.Call("addEventListener", "click", func(e *js.Object) {
		t := e.Get("target")
		print(t)
		name := o.Call("getElementById", "name")
		name.Set("value", "Hello World")
	})
}
```
### Ex 2

Example two is actually the first thing I tried.
Same as above but used godom.
The Gopherjs generated code works just fine.
But prepack won't evaluate it.

``` go
package main

//go:generate gopherjs build simple.go -o simple.js

import (
	"github.com/siongui/godom"
)

func main() {
	newDBtn := godom.Document.GetElementById("newd-btn")
	newDBtn.AddEventListener("click", func(e godom.Event) {
		print(e.Target())
		name := godom.Document.GetElementById("name")
		name.SetValue("btn")
	})
}
```

```
Errors found while prepacking
In input file /github.com/siongui/godom/eventtarget.go(13:4) FatalError PP0012: member expression object is unknown (https://github.com/facebook/prepack/wiki/PP0012)
Error
    at /github.com/siongui/godom/eventtarget.go:13:4
    at main (unknown)
    at $init (simple.js:4849:4)
    at apply (native)
    at $goroutine (simple.js:1471:15)
    at $runScheduled (simple.js:1511:7)
    at $schedule (simple.js:1527:5)
    at $go (simple.js:1503:3)
    at simple.js:4860:1
    at call (native)
    at simple.js:2:1
```

PP0012 says

> To make this error go away find out why the object is unknown and make the relevant parts environmental model more precise. For example, if the object expression refers to an environmental property that is marked as abstract in the model, refine the model so that the property is known to have an object value, preferably with some structure so that the entire member expression can be resolved.

I'm sure this means something to people who know javascript ;-)

**Comment by myitcv** [comment]
Hi @millergarym,

To my mind this request falls into the same bracket as https://github.com/gopherjs/gopherjs/issues/136 https://github.com/gopherjs/gopherjs/issues/186 https://github.com/gopherjs/gopherjs/issues/134 (and possibly others)

Generally speaking, optimisations of the output of GopherJS are best achieved by the `gopherjs` compiler itself. That is because the compiler has all the relevant (type) information available to hand, knows what code can be eliminated etc - there are still many optimisations possible, not least https://github.com/gopherjs/gopherjs/issues/186

So whether prepack works on the output of `gopherjs` code or not, is, I think, not as pressing as optimising the `gopherjs` compiler itself. 

To ask another question, assuming we squeezed everything we could out of optimisations in the `gopherjs` compiler, is there another reason you'd want to pass the output through `prepack`?

**Comment by millergarym** [comment]
@myitcv prepack does symbolic execution / partial evaluation of the code. This is sophisticated stuff and it might take years before gopherjs get to this level of optimisations. Prepack and the closure compiler have respectively Facebook and Google behind them. 

Making gopherjs output prepack friendly would be a serious shortcut.

Anyone is a position to guesstimate to the size of the issue?

**Comment by gedw99** [comment]
@millergarym good point about the LOE ( level of effort). 
Do you have a test harness anywhere using gopherjs with prepack we can look at ? 
Will be easier to do the due diligence on whats where then..

**Comment by millergarym** [comment]
@gedw99 the examples posted in this issue make a good test harness. If you would like something different, please be more specific.

**Comment by gedw99** [comment]
I agree with the other guy. Better to optimise the gopherjs compiler where the richer type info is

**Comment by millergarym** [comment]
The question remains, can anyone give a reasonable guess at the level of effort required for gopherjs to output javascript that prepack can processes.

I'm not even sure what https://github.com/facebook/prepack/wiki/PP0012 **member expression object is unknown** means.

Thinking about it, it might mean that a **less optimised compiler** is prepack friendly.
A compiler option that make says *simple, dumb, inefficient* , but one that enables prepack to really to the heavy lifting, might be an option.

Can anyone tell me, what is the relationship between gopherjs and prepack's *Unknown Abstract value*

see
https://github.com/facebook/prepack/wiki/Unknown-Abstract-value

> Prepack executes programs at compile time, when it is impossible to know the actual values of some expressions.
> 
> These values are obtained from the environmental model and are often referred to as unknown values in error messages.
> 
> Generally, however, such values are not completely unknown. We might know at compile time that a value is always a number, or perhaps that is always an object that always has a particular property that has a value that is always a number. Consequently we also refer to such values as "abstract values" to emphasize that some (but not all) information about the values have been abstracted away by the model.
> 
>

**Comment by pjebs** [comment]
https://developers.google.com/closure/compiler/

**Comment by gedw99** [comment]
Am Clueless. Can't you Chang over to wasm ? It's much easier to then integrate other packing tools I feel

**Comment by theclapp** [comment]
@millergarym is trying to reduce the size of gopherjs-generated JavaScript.  Changing to go/wasm would just shift the pain to large wasm modules, not ease it, and even make it harder to deal with, since JS tree-shakers are no doubt more mature than their wasm counterparts (if they exist at all).

Gary, I'm going to go out on a limb and presume to speak for the GopherJS maintainers and answer your initial question: 

> can anyone give a reasonable guess at the level of effort required for gopherjs to output javascript that prepack can process

And the answer is: More than anyone is willing to put in.

I think everyone will tell you that go/wasm is the future of Go on the browser (or Node), and that's where all the current eyeballs are pointed.

This doesn't really help you, and as noted really pretty much makes it worse (at the moment), but I think it's better to acknowledge reality.

All that said, check in the #webassembly Gophers Slack channel for discussion about the TinyGo dialect, which has wasm output that's downright, well, tiny — in the kilobytes range.  So there is hope.
